# Generated by Django 5.0.7 on 2024-09-01 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentalhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fine_amount', models.IntegerField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.books')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
