# Generated by Django 5.0.7 on 2024-09-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0010_remove_reportbookissue_book_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportbookissue',
            name='description',
        ),
        migrations.AddField(
            model_name='reportbookissue',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.rentalhistory'),
        ),
    ]
