# Generated by Django 5.0.7 on 2024-09-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0011_remove_reportbookissue_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportbookissue',
            name='book_name',
        ),
        migrations.AddField(
            model_name='reportbookissue',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.books'),
        ),
    ]
