# Generated by Django 5.0.7 on 2024-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0012_remove_reportbookissue_book_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='fine_payed',
            field=models.BooleanField(default=False),
        ),
    ]
