# Generated by Django 5.0.7 on 2024-09-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0015_rentalhistory_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
