# Generated by Django 5.0.7 on 2024-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0016_rentalhistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
